### ISSUE TITLE
Not all reaquire files for Smart Contract debugging generated while compiling with Neo.Compiler.MSIL console app v1.0.0.0 [DEBUGGER SUPPORT]

### ISSUE THREAD

**Issue by swdevMPaul** [Relfos/neo-debugger-tools#1]
Hello,

I have compiled the neo-debugger neo compiler tool and compiled with it a smart contract, .debug.json file generated but no .map file generated:

Here is the output of the compiler:

1>------ Rebuild All started: Project: NeoContract2, Configuration: Release Any CPU ------
1>  NeoContract2 -> D:\NEO\TestProjects\NeoContract2\NeoContract2\bin\Release\NeoContract2.dll
1>  Start NeoContract converter, Source File: D:\NEO\TestProjects\NeoContract2\NeoContract2\bin\Release\NeoContract2.dll
1>  Neo.Compiler.MSIL console app v1.0.0.0 [DEBUGGER SUPPORT]
1>  Find entrypoint:System.Int32 NeoContract2.Contract2::Main(System.String,System.Object[])
1>  convert succ
1>  gen abi succ
1>  gen debug map succ
1>  write:NeoContract2.avm
1>  write:NeoContract2.abi.json
1>  write:NeoContract2.debug.json
1>  SUCC
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========

Please tell me why ?

Can anyone upload already compiled neo-debugger-tools for Windows 10 ?

Kind Regards.

**Comment by Relfos** [comment]
The .debug.json file is what you need for latest version of the debugger.
Just open the .avm in the debugger and it all should work.

**Comment by swdevMPaul** [comment]
This is what the compiler makes:

1>------ Rebuild All started: Project: NEO-Emulator, Configuration: Release Any CPU ------
1>  NEO-Emulator -> D:\NEO\NEO_debug_tools\Newest\neo-debugger-tools-master\neo-debugger-tools-master\NEO-Emulator\bin\Release\NEO-Emulator.dll
2>------ Rebuild All started: Project: ICO-Template, Configuration: Release Any CPU ------
2>D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2041,5): warning MSB3274: The primary reference "D:\NEO\NEO_debug_tools\Newest\neo-debugger-tools-master\neo-debugger-tools-master\NEO-Emulator\bin\Release\NEO-Emulator.dll" could not be resolved because it was built against the ".NETFramework,Version=v4.7" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.6.1".
2>  ICO-Template -> D:\NEO\NEO_debug_tools\Newest\neo-debugger-tools-master\neo-debugger-tools-master\ICO-Template\bin\Release\ICOContract.dll
2>  Start NeoContract converter, Source File: D:\NEO\NEO_debug_tools\Newest\neo-debugger-tools-master\neo-debugger-tools-master\ICO-Template\bin\Release\ICOContract.dll
2>  Neo.Compiler.MSIL console app v1.0.0.0 [DEBUGGER SUPPORT]
2>  Find entrypoint:System.Object Neo.SmartContract.ICO_Template::Main(System.String,System.Object[])
2>  convert succ
2>  gen abi succ
2>  gen debug map succ
2>  write:ICOContract.avm
2>  write:ICOContract.abi.json
2>  write:ICOContract.debug.json
2>  SUCC
========== Rebuild All: 2 succeeded, 0 failed, 0 skipped ==========

Thank you for your answer Relfos.
**I need the .map file,** how to generate the .map file?

**Comment by Relfos** [comment]
The .neomap file is not generated anymore in current version. If you need it for some special reason, use this version, which is the latest that generates .neomap:
https://github.com/CityOfZion/neo-debugger-tools/tree/d8ae3f27af12f8f64471e702f75da5276cea6e12
